version: "3.8"

services:
  postgres:
    image: postgis/postgis:16-3.4
    container_name: travio-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: travio
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: travio-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  pgdata:
