-- AlterEnum
ALTER TYPE "AdminNotificationType" ADD VALUE IF NOT EXISTS 'REFUND_REQUEST';
ALTER TYPE "AdminNotificationType" ADD VALUE IF NOT EXISTS 'PAYMENT_UPCOMING';
ALTER TYPE "AdminNotificationType" ADD VALUE IF NOT EXISTS 'PAYMENT_COLLECTED';
ALTER TYPE "AdminNotificationType" ADD VALUE IF NOT EXISTS 'PAYMENT_COLLECTION_FAILED';
ALTER TYPE "AdminNotificationType" ADD VALUE IF NOT EXISTS 'STRIPE_CUSTOMER_CREATE_FAILED';
ALTER TYPE "AdminNotificationType" ADD VALUE IF NOT EXISTS 'REFUND_NEEDS_ATTENTION';
