const { PrismaClient } = require('@prisma/client');
const fs = require('fs');
const path = require('path');

function getSupabaseUrl() {
  const content = fs.readFileSync(
    path.join(__dirname, '..', '.env.supabase.backup'),
    'utf-8',
  );
  const match = content.match(/^DATABASE_URL=(.+)$/m);
  if (!match)
    throw new Error('DATABASE_URL not found in .env.supabase.backup');
  return match[1].trim();
}

const prisma = new PrismaClient({
  datasources: { db: { url: getSupabaseUrl() } },
});

function portableText(blocks) {
  return blocks.map((b, i) => ({
    _type: 'block',
    _key: `b${i}`,
    style: b.style || 'normal',
    markDefs: [],
    children: [
      {
        _type: 'span',
        _key: `s${i}`,
        text: b.text,
        marks: [],
      },
    ],
  }));
}

const CATEGORIES = [
  { name: 'Destinations', slug: 'destinations', description: 'Explore Africa\'s most captivating destinations, from iconic landmarks to hidden gems across the continent.' },
  { name: 'Adventure Travel', slug: 'adventure-travel', description: 'Thrilling adventures and bucket-list experiences for the intrepid traveller exploring Africa.' },
  { name: 'Cultural Tours', slug: 'cultural-tours', description: 'Immersive journeys into Africa\'s rich cultural heritage, traditions, and historical landmarks.' },
];

const TAGS = [
  { name: 'Victoria Falls', slug: 'victoria-falls' },
  { name: 'Mount Kilimanjaro', slug: 'mount-kilimanjaro' },
  { name: 'Serengeti', slug: 'serengeti' },
  { name: 'Safari', slug: 'safari' },
  { name: 'African Culture', slug: 'african-culture' },
  { name: 'Travel Guide', slug: 'travel-guide' },
  { name: 'Okavango Delta', slug: 'okavango-delta' },
  { name: 'Ghana', slug: 'ghana' },
];

const ARTICLES = [
  {
    title: 'Victoria Falls: The Majestic Wonder of Southern Africa',
    slug: 'victoria-falls-majestic-wonder-southern-africa',
    excerpt: 'Victoria Falls, known locally as Mosi-oa-Tunya — "The Smoke That Thunders" — stands as one of the most breathtaking natural wonders on the African continent. Straddling the border between Zambia and Zimbabwe, this magnificent waterfall plunges 108 metres into the narrow Batoka Gorge, creating a misty spectacle visible from kilometres away. During peak flood season, over 500 million litres of water cascade over the edge every minute, making it the largest sheet of falling water in the world.\n\nBeyond the falls themselves, the region offers an extraordinary range of experiences that cater to every type of traveller. Adventure seekers can bungee jump from the historic Victoria Falls Bridge, brave Grade V rapids on the Zambezi River, or take a helicopter flight over the falls for a perspective that reveals the true scale of this geological marvel. For those seeking a more tranquil experience, sunset cruises along the upper Zambezi offer encounters with hippos, elephants, and a dazzling array of birdlife against the backdrop of an African sunset.\n\nThe Victoria Falls region is also a gateway to some of Africa\'s finest wildlife experiences. Mosi-oa-Tunya National Park and the adjacent Zambezi National Park are home to elephants, buffalo, giraffes, and a wealth of bird species, while Chobe National Park in Botswana, just a short drive away, hosts the largest concentration of elephants on the continent. With a range of accommodation from the iconic Victoria Falls Hotel to luxury safari lodges and budget-friendly guesthouses, this remarkable destination offers something for every traveller seeking to witness one of the world\'s most spectacular natural wonders.',
    categorySlug: 'destinations',
    tagSlugs: ['victoria-falls', 'travel-guide'],
    readTime: 13,
    featuredImage: 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=1200&q=80',
    metaTitle: 'Victoria Falls Travel Guide | Explore Africa\'s Natural Wonder | Travio Africa',
    metaDescription: 'Complete guide to visiting Victoria Falls — best time to visit, top activities, accommodation, and travel tips for Africa\'s most spectacular waterfall.',
    body: portableText([
      { style: 'normal', text: 'Victoria Falls, known locally as Mosi-oa-Tunya — "The Smoke That Thunders" — stands as one of the most breathtaking natural wonders on the African continent. Straddling the border between Zambia and Zimbabwe, this magnificent waterfall plunges 108 metres into the narrow Batoka Gorge, creating a misty spectacle that can be seen from kilometres away. For centuries, this natural marvel has drawn travellers, explorers, and adventurers to its shores, each seeking to witness the raw power and sublime beauty of the world\'s largest curtain of falling water.' },
      { style: 'h2', text: 'The Smoke That Thunders: A Natural Marvel' },
      { style: 'normal', text: 'David Livingstone, the Scottish missionary and explorer, became the first European to lay eyes on Victoria Falls in 1855, naming it in honour of Queen Victoria. However, the indigenous Kololo people had long called it Mosi-oa-Tunya, a name that perfectly captures the ethereal mist that rises hundreds of metres into the air as the Zambezi River plunges into the chasm below. At the height of the rainy season, the spray can reach heights of over 400 metres, creating rainbows that dance across the gorge in a mesmerising display of light and water. The falls have been designated a UNESCO World Heritage Site and are protected within two national parks that preserve the surrounding wilderness for future generations.' },
      { style: 'normal', text: 'What makes Victoria Falls truly extraordinary is its sheer scale. Measuring 1,708 metres wide and 108 metres deep, it forms the largest sheet of falling water in the world. During peak flood season from February to May, over 500 million litres of water cascade over the edge every minute, creating a thunderous roar that echoes across the surrounding landscape. The force of the water has carved a series of dramatic gorges downstream, each representing a former position of the falls as the river has retreated upstream over millions of years. These gorges offer a geological timeline that adds another dimension to the visitor experience.' },
      { style: 'h2', text: 'Best Times to Visit Victoria Falls' },
      { style: 'normal', text: 'The experience of visiting Victoria Falls changes dramatically depending on the season, and each period offers a unique perspective on this natural wonder. Understanding these seasonal variations is key to planning the perfect visit. The dry season, from May to October, offers the clearest views of the falls. During these months, water levels begin to recede, revealing the intricate rock formations behind the cascading water. This is the ideal time for photography enthusiasts and those who wish to see the full geological grandeur of the gorge. The reduced spray also makes activities such as helicopter flights, bungee jumping, and white-water rafting more accessible and enjoyable.' },
      { style: 'normal', text: 'Conversely, the wet season from November to April showcases the falls at their most powerful. While the spray can obscure views from certain vantage points, the sheer force and volume of water during this period is nothing short of spectacular. Visitors during the wet season should come prepared with waterproof clothing and camera protection, as the mist permeates everything within a considerable radius. The surrounding landscape is lush and verdant, creating a stunning contrast against the white waters. Each season offers a distinctly different but equally memorable experience, and many visitors choose to return during both seasons to appreciate the full range of the falls\' character.' },
      { style: 'h2', text: 'Top Activities and Adventures' },
      { style: 'normal', text: 'Victoria Falls has rightfully earned its reputation as the adventure capital of Africa, offering an extraordinary range of activities that cater to every level of adrenaline tolerance. For the truly daring, bungee jumping from the Victoria Falls Bridge offers a 111-metre free fall into the Batoka Gorge, with the Zambezi River rushing below. The bridge itself, a remarkable feat of colonial engineering designed by Cecil Rhodes, provides a stunning vantage point for panoramic views of the gorge and the cascade beyond. The bridge also offers zip-line experiences and bridge tours that delve into its fascinating history.' },
      { style: 'normal', text: 'White-water rafting on the Zambezi River is world-renowned, featuring some of the most thrilling rapids on the planet. The stretch below the falls offers Grade V rapids with evocative names that hint at the intensity of the experience — "The Terminator," "The Muncher," and "Gnashing Jaws of Death." For those seeking a more serene experience, sunset cruises along the upper Zambezi offer a tranquil alternative, with opportunities to spot hippos, elephants, and a dazzling array of birdlife against the backdrop of an African sunset painting the sky in shades of orange and crimson. Helicopter flights over the falls, known as "The Flight of Angels," provide an unparalleled perspective of the waterfall and its intricate network of gorges.' },
      { style: 'h2', text: 'Wildlife and Natural Surroundings' },
      { style: 'normal', text: 'The national parks surrounding Victoria Falls are home to an impressive diversity of wildlife that adds another dimension to any visit. Mosi-oa-Tunya National Park on the Zambian side is a haven for elephants, buffalo, giraffes, zebras, and a variety of antelope species. The Zambezi River supports large populations of hippopotamuses and Nile crocodiles, which can often be observed basking on sandbanks or partially submerged in the shallows. Guided game drives and walking safaris offer excellent opportunities to encounter these magnificent creatures in their natural habitat, with expert guides providing insights into their behaviour, ecology, and the delicate balance of the riverine ecosystem.' },
      { style: 'normal', text: 'Bird enthusiasts will find themselves in paradise, with over 400 bird species recorded in the Victoria Falls region. The majestic African fish eagle, with its distinctive call that has become synonymous with the African wilderness, is commonly seen soaring above the river. The rare Taita falcon nests on the cliffs of the gorge, while the colourful malachite kingfisher and the striking carmine bee-eater add brilliant splashes of colour to the riverbanks. The Victoria Falls area is also one of the best places in Africa to see the elusive Pel\'s fishing owl, a large and secretive bird that hunts along the quieter stretches of the river.' },
      { style: 'h2', text: 'Where to Stay: Accommodation Options' },
      { style: 'normal', text: 'The Victoria Falls region offers a diverse range of accommodation options to suit every budget and preference. On the Zimbabwean side, the iconic Victoria Falls Hotel stands as a testament to colonial grandeur, offering unparalleled views of the bridge and gorge from its manicured lawns. For those seeking luxury safari experiences, properties such as the Matetsi River Lodge and the Elephant Camp provide world-class service combined with proximity to wildlife-rich private reserves and exceptional guiding that consistently receives rave reviews from discerning travellers.' },
      { style: 'normal', text: 'On the Zambian side, the Royal Livingstone Hotel offers a sophisticated retreat overlooking the Zambezi River, with zebras and giraffes roaming freely across the grounds. Budget-conscious travellers will find excellent options in the town of Livingstone, with a range of lodges, guesthouses, and backpacker hostels that provide comfortable accommodation without compromising on the African experience. For the ultimate indulgence, the private islands above the falls offer exclusive dining and accommodation experiences under the stars that are truly unforgettable and represent the pinnacle of African luxury hospitality.' },
      { style: 'h2', text: 'Nearby Attractions and Day Trips' },
      { style: 'normal', text: 'Beyond the falls themselves, the region offers a wealth of attractions that merit exploration and extend the scope of any visit. Chobe National Park in Botswana, just a short drive from Victoria Falls, is renowned for hosting the largest concentration of elephants on the African continent. Day trips to Chobe offer exceptional game viewing, particularly along the Chobe River where herds of elephants, buffalo, and a multitude of other species congregate in spectacular numbers. The park is also famous for its prolific predator population, including lions, leopards, and African wild dogs.' },
      { style: 'normal', text: 'The Victoria Falls Bridge itself is a historical landmark worth exploring in its own right, with guided tours that provide fascinating insights into its construction, engineering, and colourful history. For those interested in local culture, guided visits to surrounding villages offer insights into the traditional lifestyles, crafts, and customs of the Tonga and Ndebele people who have inhabited this region for centuries. The Victoria Falls Craft Village and local markets offer opportunities to purchase authentic African art, sculptures, and textiles while supporting local artisans and communities.' },
      { style: 'h2', text: 'Practical Travel Tips' },
      { style: 'normal', text: 'Visitors to Victoria Falls should be aware that both Zimbabwe and Zambia require valid visas for most nationalities, which can often be obtained on arrival. However, we recommend checking the latest visa requirements well in advance of travel, as regulations can change. The region enjoys a subtropical climate, with temperatures ranging from 18°C to 32°C throughout the year. Lightweight, breathable clothing is recommended, along with sturdy walking shoes for exploring the falls trails. A raincoat or poncho is essential during the wet season, and insect repellent is advisable year-round for protection against mosquitoes and other biting insects.' },
      { style: 'normal', text: 'The currency situation in Zimbabwe has stabilised in recent years, with the US dollar being widely accepted alongside the local currency. Zambia uses the Zambian kwacha. ATMs are available in both towns, but carrying sufficient cash for activities and local purchases is advisable, as card facilities can be unreliable in certain establishments. For the most comprehensive experience, we recommend allocating at least three to four days to fully appreciate all that this remarkable destination has to offer. Whether you come for the adventure, the natural beauty, or the profound sense of wonder that has drawn travellers for generations, Victoria Falls delivers an experience that lingers long after you have returned home.' },
    ]),
  },
  {
    title: 'Ascending the Roof of Africa: A Complete Guide to Climbing Mount Kilimanjaro',
    slug: 'ascending-roof-africa-climbing-mount-kilimanjaro-guide',
    excerpt: 'Mount Kilimanjaro rises majestically from the Tanzanian plains, its snow-capped summit piercing the African sky at an elevation of 5,895 metres. As the highest peak on the African continent and the tallest free-standing mountain in the world, Kilimanjaro has long captured the imagination of adventurers, trekkers, and dreamers from every corner of the globe. Unlike many of the world\'s great mountains, Kilimanjaro requires no technical climbing skills, making it accessible to anyone with reasonable fitness and determination, yet the challenge it presents is both physical and psychological — a test of endurance, willpower, and human spirit.\n\nChoosing the right route is one of the most critical decisions in planning a successful Kilimanjaro expedition. The Marangu Route offers hut accommodation and is the only route with this comfort, while the Machame Route, known as the "Whiskey Route," is the most popular for its excellent acclimatisation profile. The Lemosho Route provides a more remote and scenic alternative with lower traffic levels, and the Northern Circuit Route offers the highest summit success rates thanks to its longer duration and superior acclimatisation profile. Whichever route you choose, selecting an itinerary of seven days or more dramatically improves your chances of reaching the summit.\n\nPreparation for Kilimanjaro should begin several months before departure, combining cardiovascular training, strength work, and practice hikes with a weighted backpack to simulate the demands of consecutive days at altitude. Packing is equally critical — effective layering is essential to cope with temperature ranges from 30°C in the rainforest to minus 15°C at the summit. Beyond the physical preparation, climbing Kilimanjaro is a cultural experience that connects you with the warmth and professionalism of the Tanzanian people, particularly the Chagga communities and the porters, guides, and cooks who make the impossible possible for thousands of climbers every year.',
    categorySlug: 'adventure-travel',
    tagSlugs: ['mount-kilimanjaro', 'travel-guide'],
    readTime: 15,
    featuredImage: 'https://images.unsplash.com/photo-1540979388789-6cee28a1cdc9?w=1200&q=80',
    metaTitle: 'Climbing Mount Kilimanjaro Guide | Routes, Tips & Preparation | Travio Africa',
    metaDescription: 'Everything you need to know about climbing Mount Kilimanjaro — route comparisons, altitude preparation, packing lists, and expert tips for reaching Africa\'s highest summit.',
    body: portableText([
      { style: 'normal', text: 'Mount Kilimanjaro rises majestically from the Tanzanian plains, its snow-capped summit piercing the African sky at an elevation of 5,895 metres. As the highest peak on the African continent and the tallest free-standing mountain in the world, Kilimanjaro has long captured the imagination of adventurers, trekkers, and dreamers from every corner of the globe. Unlike many of the world\'s great mountains, Kilimanjaro requires no technical climbing skills, making it accessible to anyone with reasonable fitness and determination. Yet the challenge it presents is both physical and psychological — a test of endurance, willpower, and human spirit that pushes climbers to their limits and rewards them with an experience that transforms their understanding of what they are capable of achieving.' },
      { style: 'h2', text: 'Understanding the Mountain' },
      { style: 'normal', text: 'Kilimanjaro is not merely a mountain but a massive stratovolcano composed of three distinct cones: Kibo, Mawenzi, and Shira. Kibo, the highest of the three, is also the only one that remains dormant rather than extinct, with the potential to erupt again in the distant future. The summit, known as Uhuru Peak, sits on the crater rim of Kibo and offers breathtaking views of the surrounding plains and the glaciers that have capped the mountain for millennia. These glaciers, sadly, have been receding at an alarming rate due to climate change, making a visit to the summit increasingly urgent for those who wish to witness them before they disappear entirely.' },
      { style: 'normal', text: 'What makes Kilimanjaro unique is the extraordinary range of ecological zones climbers traverse on their journey to the summit. Beginning in lush tropical rainforest at the base, the ascent passes through heath and moorland, alpine desert, and finally the arctic zone near the summit. Each zone supports its own distinct flora and fauna, transforming the climb into an immersive natural history experience. Trekkers may encounter colobus monkeys leaping through the canopy in the rainforest, glimpse the unique giant lobelias and groundsels of the moorland, and marvel at the stark, otherworldly beauty of the alpine desert before reaching the snow and ice of the summit zone.' },
      { style: 'h2', text: 'Choosing Your Route' },
      { style: 'normal', text: 'Selecting the right route is one of the most critical decisions in planning a Kilimanjaro expedition. Each of the seven official routes offers a different experience in terms of scenery, difficulty, traffic levels, and, most importantly, acclimatisation profiles. The Marangu Route, often called the "Coca-Cola Route," is the only route with hut accommodation and is generally considered the easiest, though its rapid ascent profile results in lower summit success rates compared to longer itineraries. The route approaches from the southeast and follows a relatively direct path to the summit, making it popular with first-time climbers and those seeking hut-based comfort.' },
      { style: 'normal', text: 'The Machame Route, known as the "Whiskey Route," is the most popular and is widely recommended for its excellent acclimatisation profile following the principle of "climb high, sleep low." This route approaches from the south and traverses diverse landscapes, including the stunning Barranco Valley with its towering walls and the dramatic Great Barranco Wall, a steep but non-technical scramble that adds an element of adventure. The Lemosho Route offers a more remote and scenic alternative, with lower traffic levels and exceptional views across the Shira Plateau. For those seeking solitude, the Northern Circuit Route provides the most time for acclimatisation and traverses the quieter northern slopes of the mountain, offering the highest summit success rates of any route.' },
      { style: 'normal', text: 'The Rongai Route is the only route approaching from the north and offers a unique perspective, particularly during the rainy season when it receives less precipitation than the southern routes. The Umbwe Route, while spectacularly scenic, is the most technically challenging and steep, with limited time for acclimatisation, making it suitable only for experienced trekkers in excellent physical condition. Whichever route you choose, we strongly recommend selecting a longer itinerary of seven days or more to optimise your chances of reaching the summit and to allow sufficient time for proper acclimatisation.' },
      { style: 'h2', text: 'Best Time to Climb' },
      { style: 'normal', text: 'Kilimanjaro can be climbed year-round, but the best conditions generally occur during the two primary dry seasons. The first dry season runs from January to March, offering clear skies, stable weather, and excellent visibility. The temperatures are cooler during these months, making for more comfortable trekking conditions, particularly on the upper slopes. The second and most popular dry season extends from June to October, with August and September being the absolute peak months when the weather is most predictable, with minimal rainfall and the best chances of clear summit views.' },
      { style: 'normal', text: 'The long rainy season from March to May is generally avoided by most climbers due to wet, slippery trails, limited visibility, and significantly lower summit success rates. However, the short rainy season in November presents a mixed picture — while there is increased precipitation, the crowds are thinner, the landscapes are lush and vibrant, and many trekkers appreciate the solitude. December offers favourable conditions on the northern routes, though the southern routes can experience significant rainfall. Ultimately, the best time to climb depends on your priorities regarding weather, crowds, and budget.' },
      { style: 'h2', text: 'Preparing for the Climb' },
      { style: 'normal', text: 'Preparation for Kilimanjaro should begin several months before your scheduled departure. While the climb does not require technical mountaineering skills, it demands excellent cardiovascular fitness and muscular endurance. A training programme combining long-distance hiking with a weighted backpack, stair climbing, and regular cardiovascular exercise will build the necessary stamina. We recommend progressively increasing the duration and intensity of your training to simulate the demands of consecutive days of hiking at altitude. Incorporating strength training for the legs and core will also prove beneficial, as will practising with trekking poles to develop muscle memory and efficiency.' },
      { style: 'normal', text: 'Packing appropriately is equally essential. The key to a successful Kilimanjaro climb lies in effective layering — the temperature on the mountain can range from 30°C in the rainforest to minus 15°C at the summit, and conditions can change dramatically within hours. A quality four-season sleeping bag rated to at least minus 20°C is essential, as are thermal base layers, insulating mid-layers, and a waterproof and windproof outer shell. Good quality trekking boots that are well broken-in, trekking poles, and a reliable headlamp with spare batteries are non-negotiable items that can make the difference between a successful climb and a miserable experience.' },
      { style: 'h2', text: 'What to Expect Each Day' },
      { style: 'normal', text: 'A typical Kilimanjaro trek follows a rhythm that becomes familiar over the course of the expedition. Each day begins early, usually around 6:00 AM, with a hearty breakfast in the mess tent. The daily hiking distance varies from 5 to 18 kilometres, with elevation gains ranging from 300 to 1,200 metres. The mantra "pole pole" (slowly, slowly in Swahili) guides the pace, encouraging climbers to conserve energy and facilitate acclimatisation. Porters carry the bulk of the gear, allowing trekkers to focus on the trail and their breathing. The afternoons bring a chance to rest at camp, enjoy hot drinks, and take in the spectacular views before dinner and an early night under the African stars.' },
      { style: 'normal', text: 'Summit night is the most demanding part of the expedition and is an experience that will test every fibre of your being. Beginning around midnight, climbers make their way to the summit by headlamp, navigating steep switchbacks and scree slopes in freezing temperatures and thin air. The ascent to Uhuru Peak typically takes six to eight hours, followed by a three-hour descent to the nearest high camp. The sense of accomplishment upon reaching the summit is overwhelming, with the sunrise over the African continent providing a backdrop that words cannot adequately describe. Many climbers describe this moment as the most profound and emotional experience of their entire lives.' },
      { style: 'h2', text: 'Altitude Acclimatisation and Safety' },
      { style: 'normal', text: 'Altitude sickness is the single greatest challenge faced by Kilimanjaro climbers and the primary reason for failed summit attempts. The principle of "climb high, sleep low" guides the design of the best itineraries, allowing the body to gradually adjust to decreasing oxygen levels. Diamox (acetazolamide) is commonly used to prevent and manage symptoms of acute mountain sickness, but should only be taken under medical supervision after consulting with a travel health specialist. Reputable operators carry portable oxygen monitors, comprehensive first aid kits, and supplemental oxygen for emergencies, with established evacuation protocols in place.' },
      { style: 'normal', text: 'Understanding the symptoms of altitude sickness is crucial for every climber. Mild symptoms include headache, nausea, dizziness, and fatigue, which can often be managed with rest, hydration, and medication. However, more severe symptoms such as confusion, loss of coordination, and respiratory distress require immediate descent. Successful summiters consistently emphasise the importance of hydration, proper nutrition, and listening to one\'s body throughout the climb. The mountain will always be there — there is no shame in turning back if conditions or your body dictate that descent is the wisest course of action.' },
      { style: 'h2', text: 'Costs and Booking Considerations' },
      { style: 'normal', text: 'The cost of climbing Kilimanjaro varies significantly depending on the route, duration, and level of service, with prices typically ranging from $2,000 to $6,000 per person for a seven-day climb. Budget-conscious trekkers should be wary of extremely low prices, which often indicate corners being cut on safety equipment, food quality, or most troublingly, porter welfare. The Kilimanjaro Porter Assistance Project has worked tirelessly to establish minimum standards for the treatment of porters, and choosing an operator that adheres to these guidelines is both ethical and essential for a successful climb.' },
      { style: 'normal', text: 'All climbers must book through a licensed tour operator registered with the Kilimanjaro National Park Authority. Park fees, rescue fees, and VAT account for a significant portion of the total cost, which explains why budget operators offering seemingly identical itineraries at substantially lower prices are often cutting essential corners. We recommend booking at least six months in advance, particularly for the popular January and August climbing windows, and thoroughly researching operators through reputable review platforms and climbing forums to ensure you choose a company with a proven track record of safety and success.' },
      { style: 'h2', text: 'The Cultural Experience' },
      { style: 'normal', text: 'The communities surrounding Kilimanjaro, particularly the Chagga people, have a rich cultural heritage that adds meaningful depth to the climbing experience. Many itineraries include visits to Chagga villages, where trekkers can explore banana and coffee plantations, visit traditional homes built from local materials, and learn about the customs and traditions that have sustained these communities for generations. The Chagga people are renowned for their sophisticated irrigation systems, terraced farming techniques, and vibrant cultural festivals that celebrate their history and identity.' },
      { style: 'normal', text: 'The porters, guides, and cooks who accompany climbers are predominantly from the local communities surrounding the mountain, and their expertise, resilience, and warmth are integral to the Kilimanjaro experience. Choosing an operator that adheres to the Kilimanjaro Porter Assistance Project guidelines ensures fair wages, proper equipment, and respectful treatment for these essential team members. Many climbers find that the relationships they build with their crew become the most treasured memories of the entire expedition, a testament to the extraordinary hospitality and professionalism of the Tanzanian people who make the impossible possible every single day.' },
      { style: 'normal', text: 'Climbing Kilimanjaro is a transformative experience that challenges the body, strengthens the spirit, and leaves an indelible mark on the soul. Standing atop the Roof of Africa, looking out over a continent of extraordinary diversity and beauty, you will understand why this mountain has inspired awe and ambition since the first recorded ascent in 1889. The journey demands much, but it rewards infinitely more, and those who undertake it emerge with a profound appreciation for the power of the human spirit and the majestic beauty of the natural world.' },
    ]),
  },
  {
    title: 'The Great Migration: Witnessing Nature\'s Greatest Spectacle in the Serengeti',
    slug: 'great-migration-witnessing-natures-greatest-spectacle-serengeti',
    excerpt: 'The Great Migration of the Serengeti is widely regarded as the most spectacular wildlife event on the planet. Each year, more than 1.5 million wildebeest, accompanied by hundreds of thousands of zebras and gazelles, embark on a continuous, circular journey of approximately 800 kilometres across Tanzania and Kenya in search of fresh grazing and water. This ancient pilgrimage, driven by the rhythms of rainfall and the seasons, has unfolded for millennia and represents one of the last great migratory systems on Earth — a raw, unfiltered display of nature at its most magnificent.\n\nThe migration follows a predictable annual pattern that offers distinct wildlife spectacles throughout the year. From December to March, the herds congregate on the short grass plains of the southern Serengeti for the calving season, when approximately 8,000 wildebeest calves are born each day, creating a bonanza for predators. By June and July, the migration reaches the crocodile-infested Grumeti River, where the first dramatic river crossings occur. The most famous crossings take place from August to October at the Mara River in the northern Serengeti, where thousands of animals plunge into turbulent waters while massive Nile crocodiles lie in wait — arguably the most dramatic wildlife encounter Africa has to offer.\n\nA successful Great Migration safari requires careful planning, patience, and the right choice of operator and accommodation. We recommend booking at least six to twelve months in advance, particularly for the peak months from July to October when demand is highest. Mobile camps that move with the herds offer the most immersive experience, while permanent lodges in key locations provide greater comfort and reliability. With an experienced guide who understands the rhythms of the migration, visitors have the opportunity to witness one of Earth\'s most extraordinary natural phenomena — an experience that is nothing short of life-changing.',
    categorySlug: 'adventure-travel',
    tagSlugs: ['serengeti', 'safari'],
    readTime: 14,
    featuredImage: 'https://images.unsplash.com/photo-1506466010722-395aa2bef877?w=1200&q=80',
    metaTitle: 'The Great Migration Safari Guide | Serengeti Wildebeest Migration | Travio Africa',
    metaDescription: 'Complete guide to witnessing the Great Migration in the Serengeti — when and where to see the wildebeest crossing, safari tips, and the best camps for an unforgettable wildlife experience.',
    body: portableText([
      { style: 'normal', text: 'The Great Migration of the Serengeti is widely regarded as the most spectacular wildlife event on the planet. Each year, more than 1.5 million wildebeest, accompanied by hundreds of thousands of zebras and gazelles, embark on a continuous, circular journey of approximately 800 kilometres across Tanzania and Kenya in search of fresh grazing and water. This ancient pilgrimage, driven by the rhythms of rainfall and the seasons, has unfolded for millennia and represents one of the last great migratory systems on Earth. To witness it is to connect with something primal and profound — a reminder of the wild, untamed beauty that still exists in our increasingly developed world.' },
      { style: 'h2', text: 'The Greatest Show on Earth' },
      { style: 'normal', text: 'To witness the Great Migration is to observe nature in its most elemental form. The herds move in a vast, pulsating mass that stretches across the plains, their hooves creating a low, continuous thunder that reverberates through the earth. Predators follow in their wake — lions, leopards, cheetahs, hyenas, and wild dogs — each seizing the opportunity presented by this extraordinary concentration of prey. The drama that unfolds is both brutal and beautiful, a testament to the relentless cycle of life and death that defines the African wilderness. Every moment offers something remarkable, from the heart-wrenching vulnerability of newborn calves to the breathtaking speed and precision of a predator\'s hunt.' },
      { style: 'normal', text: 'The migration is not a single event but a continuous process that varies in intensity and location throughout the year. The herds do not move as a single, coordinated unit but rather in a series of waves and clusters, with different groups at different stages of the journey at any given time. This makes the migration unpredictable and adds an element of serendipity to the safari experience — no two visits are ever the same, and even the most experienced guides cannot guarantee what will unfold on any given day. It is this unpredictability that makes witnessing the migration such a profoundly authentic experience.' },
      { style: 'h2', text: 'Understanding the Migration Cycle' },
      { style: 'normal', text: 'The migration follows a predictable annual pattern that is intimately tied to the region\'s rainfall cycles and the subsequent growth of nutrient-rich grass. From December to March, the herds congregate on the short grass plains of the southern Serengeti and the Ndutu area, where the volcanic soils produce the most nutritious grass on the entire migration route. This is the calving season, when approximately 8,000 wildebeest calves are born each day over a period of several weeks, creating a bonanza for the predators that patrol these plains. The concentration of predator activity during this period is nothing short of extraordinary.' },
      { style: 'normal', text: 'Around April to May, as the southern plains dry out and the nutrient levels in the grass decline, the herds begin their north-westward movement towards the central Serengeti and the Western Corridor. By June to July, the migration reaches the Grumeti River, where the first major river crossings of the year occur. The crocodile-infested waters present a formidable obstacle, and the crossings are among the most dramatic and photogenic moments of the entire migration cycle. The tension is palpable as thousands of animals gather on the riverbanks, hesitating before the first brave individual plunges into the water, triggering a chaotic surge of bodies.' },
      { style: 'normal', text: 'The most famous crossings occur from August to October, when the herds reach the Mara River in the northern Serengeti in Tanzania and the Maasai Mara in Kenya. These crossings are the climax of the migration, with thousands of animals plunging into the turbulent waters in a desperate surge, while massive Nile crocodiles lie in wait. The crossings are unpredictable and can occur at any time of day, requiring patience and persistence from those hoping to witness them. The rewards for those who wait are extraordinary — a raw, unfiltered display of nature\'s power that stays with you for the rest of your life.' },
      { style: 'h2', text: 'Best Times and Locations for Viewing' },
      { style: 'normal', text: 'The optimal viewing location and timing depend entirely on what aspect of the migration you wish to experience. For the calving season, the southern Serengeti and Ndutu area from December to March offers extraordinary wildlife viewing, with abundant predator action and the heartwarming sight of newborn calves taking their first wobbly steps. This period coincides with the dry season in southern Serengeti, making wildlife easier to spot as animals congregate around water sources. The short grass provides exceptional visibility, and the golden light of the African sun creates perfect conditions for photography.' },
      { style: 'normal', text: 'For the river crossings, the Western Corridor and Grumeti River is best from June to July, while the northern Serengeti and Mara River offers the most dramatic crossings from August to October. The Maasai Mara in Kenya also offers exceptional viewing from July to October when the herds are in residence. For those seeking a combination of excellent game viewing and fewer crowds, the shoulder months of May and November offer excellent value and unique perspectives on the migration, with the herds on the move and storm clouds building on the horizon in a dramatic display of nature\'s power.' },
      { style: 'h2', text: 'Safari Tips for the Ultimate Experience' },
      { style: 'normal', text: 'A successful Great Migration safari requires careful planning and realistic expectations. We recommend booking at least six to twelve months in advance, particularly for the peak months from July to October when demand is highest and the best camps are fully booked far ahead. Choosing the right accommodation is crucial — mobile camps that move with the herds offer the most immersive experience, allowing you to stay at the heart of the action, while permanent lodges provide greater comfort and reliability. Many experienced travellers opt for a combination of both to cover different phases of the migration across multiple regions.' },
      { style: 'normal', text: 'Patience is perhaps the most important attribute for a migration safari. River crossings can involve hours of waiting under the African sun, and the herds do not perform on schedule. An experienced guide who maintains communication with other guides across the ecosystem can significantly enhance your chances of being in the right place at the right time. Morning and late afternoon game drives offer the best light and the most active wildlife, with the midday hours best spent relaxing at camp, enjoying a good book, and recharging for the next adventure.' },
      { style: 'h2', text: 'Photography Tips for the Migration' },
      { style: 'normal', text: 'Capturing the Great Migration through photography requires preparation, patience, and the right equipment. A telephoto lens of at least 200-400mm is essential for river crossing shots, allowing you to capture the drama from a safe and respectful distance while maintaining the ability to isolate subjects from the background. For sweeping landscape and herd shots, a wide-angle lens is invaluable for conveying the sheer scale of the migration — the endless columns of animals stretching across the plains is a sight that demands to be captured in its full context.' },
      { style: 'normal', text: 'The best light for photography occurs during the golden hours of early morning and late afternoon, when the warm, directional light creates depth, texture, and atmosphere in your images. River crossings often occur in the early morning or late afternoon light, creating opportunities for truly memorable images. A camera with good high-ISO performance is advantageous for these low-light conditions, and a sturdy bean bag or monopod for use in vehicles will help ensure sharp images. Remember to take time to simply watch and absorb the experience without a camera — the most profound memories are often the ones you carry in your heart.' },
      { style: 'h2', text: 'Choosing the Right Safari Operator' },
      { style: 'normal', text: 'The quality of your migration experience depends heavily on your choice of safari operator. Look for companies with experienced guides who have deep knowledge of the Serengeti ecosystem and a proven track record of exceptional wildlife encounters. The guide-to-guest ratio matters significantly — smaller groups ensure a more personalised experience, better vehicle positioning for photography, and a lower impact on the environment. A good guide is worth their weight in gold, combining encyclopaedic knowledge with an intuitive sense of where the herds are moving.' },
      { style: 'normal', text: 'Consider operators who contribute to conservation and local community initiatives, ensuring that your visit has a positive impact beyond the immediate safari experience. Certifications such as Gold Eco-Rating from the Tanzania Tourist Board or membership in responsible tourism organisations indicate a genuine commitment to sustainable practices. Reading recent reviews from past guests who travelled during the same season you are considering provides valuable insights into what you can expect and helps you make an informed decision about one of the most significant travel investments you will ever make.' },
      { style: 'h2', text: 'Accommodation Types and Recommendations' },
      { style: 'normal', text: 'The Serengeti offers an impressive range of accommodation to suit different preferences and budgets, from luxurious permanent lodges to intimate mobile camps that move with the herds. Permanent lodges provide consistent comfort, often featuring swimming pools, spa facilities, and exceptional dining, making them ideal for those who value creature comforts after a day on safari. Properties such as Singita Grumeti, Four Seasons Safari Lodge Serengeti, and Serengeti Bushtops represent the pinnacle of luxury, offering suites that rival the world\'s finest hotels.' },
      { style: 'normal', text: 'Mobile camps offer a more authentic and immersive experience, with lightweight tented accommodation that can be assembled and disassembled as the herds move across the landscape. Camps such as Nomad Serengeti Safari Camp and Olakira Migration Camp specialise in following the migration, ensuring that you are always positioned at the heart of the action. The Serengeti is divided into different zones, each offering a unique safari experience — the central Seronera area is famous for year-round game viewing, while the northern Serengeti provides the best access to the Mara River crossings.' },
      { style: 'h2', text: 'Conservation and Responsible Tourism' },
      { style: 'normal', text: 'The Great Migration is not only a natural wonder but also a vital economic engine for conservation in East Africa. Tourism revenue directly supports the protection of the Serengeti-Mara ecosystem, funds anti-poaching efforts, and provides livelihoods for thousands of local communities living adjacent to the protected areas. The migration\'s survival depends on the continued connectivity of the ecosystem, which requires collaboration between Tanzania and Kenya, as well as between governments, conservation organisations, and local communities.' },
      { style: 'normal', text: 'Choosing responsible tour operators who adhere to ethical wildlife viewing practices, employ local guides and staff, and contribute to community conservation initiatives ensures that your visit has a positive impact on the region. Simple actions such as maintaining a respectful distance from wildlife, staying on designated tracks, and never interfering with natural behaviours contribute to the long-term sustainability of this extraordinary phenomenon. For those who make the journey to witness it, the Great Migration offers an experience that is nothing short of life-changing.' },
    ]),
  },
  {
    title: 'Exploring the Rich Heritage of Ghana\'s Cape Coast and Elmina Castles',
    slug: 'exploring-rich-heritage-ghana-cape-coast-elmina-castles',
    excerpt: 'Along the sun-drenched coast of southern Ghana, two formidable fortresses stand as solemn monuments to one of history\'s most painful chapters. Cape Coast Castle and Elmina Castle, both UNESCO World Heritage Sites, are among the most significant historical landmarks in West Africa. Their thick stone walls have witnessed centuries of trade, conflict, and human suffering, but they also stand as powerful symbols of resilience, remembrance, and the unbreakable spirit of the African people. A visit to these castles is not merely a tour but a profound emotional and educational journey that connects visitors to a history that continues to shape the modern world.\n\nThe history of these coastal fortifications is inextricably linked to the transatlantic slave trade, one of the darkest periods in human history. Between the 15th and 19th centuries, European powers constructed approximately 40 forts and castles along Ghana\'s 500-kilometre coastline. Elmina Castle, built by the Portuguese in 1482, is the oldest European building in Africa south of the Sahara, while Cape Coast Castle later became the epicentre of British colonial administration in the Gold Coast. The dungeons where enslaved Africans were held remain preserved in their original state, with the "Door of No Return" at Cape Coast Castle standing as one of the most emotionally charged historical sites anywhere in the world.\n\nBeyond their historical significance, these castles have become powerful symbols of the African diaspora\'s connection to the continent. The Ghanaian government\'s "Year of Return" initiative in 2019 transformed Ghana into a global hub for diaspora tourism, with the castles serving as sacred pilgrimage sites for African descendants from around the world. Visitors to Cape Coast and Elmina can also explore the vibrant local culture, sample exceptional Ghanaian cuisine, visit Kakum National Park with its famous canopy walkway, and experience the warm hospitality of a nation that has turned its painful history into a message of reconciliation, hope, and unity.',
    categorySlug: 'cultural-tours',
    tagSlugs: ['african-culture', 'ghana', 'travel-guide'],
    readTime: 13,
    featuredImage: 'https://images.unsplash.com/photo-1580651315530-69c8e0026377?w=1200&q=80',
    metaTitle: 'Cape Coast & Elmina Castles Guide | Ghana\'s Historical Heritage | Travio Africa',
    metaDescription: 'Discover the history and significance of Cape Coast Castle and Elmina Castle in Ghana — guided tours, cultural impact, and essential travel information for these powerful UNESCO sites.',
    body: portableText([
      { style: 'normal', text: 'Along the sun-drenched coast of southern Ghana, two formidable fortresses stand as solemn monuments to one of history\'s most painful chapters. Cape Coast Castle and Elmina Castle, both UNESCO World Heritage Sites, are among the most significant historical landmarks in West Africa. Their thick stone walls have witnessed centuries of trade, conflict, and human suffering, but they also stand as powerful symbols of resilience, remembrance, and the unbreakable spirit of the African people. A visit to these castles is not merely a tour but a profound emotional and educational journey that connects visitors to a history that continues to shape the modern world.' },
      { style: 'h2', text: 'A Journey into History' },
      { style: 'normal', text: 'The history of the coastal castles of Ghana is inextricably linked to the transatlantic slave trade, one of the darkest periods in human history. Between the 15th and 19th centuries, European powers — including the Portuguese, Dutch, British, Swedish, and Danish — constructed approximately 40 forts and castles along Ghana\'s 500-kilometre coastline. These fortifications served as trading posts for gold, ivory, and, most tragically, human beings. Elmina Castle, built by the Portuguese in 1482, is the oldest European building in Africa south of the Sahara, while Cape Coast Castle, originally constructed by the Swedes in 1653, later became the epicentre of British colonial administration in the Gold Coast.' },
      { style: 'normal', text: 'These castles were meticulously designed as instruments of commerce and control, with thick walls, mounted cannons, and strategically positioned ramparts that reflected the military architecture of their European builders. Yet their most harrowing features lie below ground level. The dungeons where enslaved Africans were held in unimaginable conditions before being loaded onto ships for the Middle Passage remain preserved in their original state, offering visitors a visceral connection to the horrors of the slave trade. The "Door of No Return" at Cape Coast Castle — the final passage through which captives exited African soil — stands as one of the most emotionally charged historical sites anywhere in the world.' },
      { style: 'h2', text: 'Cape Coast Castle: The Door of No Return' },
      { style: 'normal', text: 'Cape Coast Castle is the most visited of Ghana\'s historical castles, drawing hundreds of thousands of visitors annually, including heads of state, celebrities, and descendants of enslaved Africans making a pilgrimage of return. The castle\'s guided tour is a deeply moving experience that takes visitors through the male and female dungeons, where up to 1,000 captives were confined in appalling conditions with minimal ventilation, sanitation, or food. Above these dungeons, the colonial governor\'s quarters and the castle church stand in stark juxtaposition — a chilling reminder of the moral contradictions that underpinned the slave trade and the depths of human cruelty.' },
      { style: 'normal', text: 'The museum within Cape Coast Castle houses an extensive collection of artefacts, documents, and exhibits that trace the history of the slave trade, the cultures of the enslaved peoples, and the lasting impact of the African diaspora on the Americas, Europe, and the world. Interactive displays, archival materials, and educational programmes provide historical context and invite reflection on the global significance of the site. For many visitors of African descent, the tour culminates in an emotionally powerful ceremony at the Door of No Return, where names are read, prayers are offered, and a symbolic return through the door represents a reclaiming of heritage, identity, and ancestral connection.' },
      { style: 'h2', text: 'Elmina Castle: Africa\'s Oldest European Building' },
      { style: 'normal', text: 'Elmina Castle, or St. George\'s Castle as it was originally named, predates Cape Coast Castle by nearly two centuries and offers a different but equally compelling perspective on the history of European-African interaction. Built by the Portuguese in 1482, the castle was initially established as a trading post for gold, ivory, and spices — commodities that drew European powers to the West African coast long before the slave trade became the dominant commerce. The castle\'s architecture reflects its Portuguese origins, with distinctive Manueline-style windows and a chapel that stands as one of the oldest Christian places of worship in sub-Saharan Africa.' },
      { style: 'normal', text: 'The tour of Elmina Castle is equally harrowing, guiding visitors through the cramped dungeons, the punishment cell, and the courtyard where enslaved people were bought and sold. The castle\'s location on a peninsula jutting into the Atlantic Ocean provides stunning coastal views that belie the darkness of its history. The adjacent town of Elmina, with its colourful fishing harbour, bustling markets, and vibrant local culture, offers visitors the opportunity to explore a living community that has evolved alongside the castle for over five centuries, creating a unique blend of European and African heritage.' },
      { style: 'h2', text: 'Architecture and Design of the Castles' },
      { style: 'normal', text: 'The architectural design of Cape Coast and Elmina Castles reflects both European military engineering and the brutal economic logic of the slave trade. Thick stone walls, bastions, and strategically positioned gun emplacements were designed to withstand attacks from rival European powers and protect the valuable human cargo held within. The layout of each castle deliberately separated the commercial and residential quarters from the holding dungeons, creating a physical and psychological distance that allowed the castle\'s inhabitants to maintain the fiction of civilised order while participating in one of history\'s greatest atrocities.' },
      { style: 'normal', text: 'Elmina Castle\'s architectural evolution traces the transition from Portuguese to Dutch and finally British control, with each colonial power adding their own modifications and improvements. The castle\'s distinctive whitewashed walls, red-tiled roofs, and arched doorways reflect its Portuguese origins, while the later Dutch additions introduced characteristic gables and more functional military structures. The chapel within the castle, with its simple altar and weathered wooden pews, offers a poignant contrast between the spiritual aspirations of the European occupants and the brutal reality of the commerce conducted within the castle walls.' },
      { style: 'h2', text: 'Cultural Impact and Modern-Day Significance' },
      { style: 'normal', text: 'The legacy of the castles extends far beyond their historical role in the slave trade. In recent decades, they have become powerful symbols of the African diaspora\'s connection to the continent and focal points for cultural reconciliation and healing. The Ghanaian government\'s "Year of Return" initiative in 2019 and the subsequent "Beyond the Return" campaign have transformed Ghana into a global hub for diaspora tourism, with the castles serving as sacred pilgrimage sites for African Americans, Afro-Caribbeans, and people of African descent from around the world seeking to reconnect with their ancestral heritage.' },
      { style: 'normal', text: 'The castles also serve as vital educational resources, hosting international conferences, academic workshops, and cultural events that address contemporary issues of racial justice, human rights, and historical reconciliation. The Panafest festival, held biennially in Ghana, incorporates the castles into its programme of theatrical performances, lectures, music, and commemorative ceremonies that celebrate African culture and promote continental unity. For Ghanaian schoolchildren, a visit to the castles is an essential part of their national education, ensuring that future generations understand the full complexity of their nation\'s history and its place in the world.' },
      { style: 'h2', text: 'Ghanaian Cuisine and Local Experiences' },
      { style: 'normal', text: 'No visit to Ghana\'s Central Region is complete without sampling the rich and diverse local cuisine that reflects the country\'s cultural heritage and coastal location. The fishing towns of Cape Coast and Elmina offer exceptional seafood, with freshly caught tilapia, red snapper, lobster, and prawns featuring prominently on menus throughout the region. Traditional Ghanaian dishes such as fufu and light soup, jollof rice, banku with fried fish and shito, and groundnut soup are essential culinary experiences that connect visitors to the daily rhythms and traditions of Ghanaian life.' },
      { style: 'normal', text: 'Local markets in Cape Coast and Elmina offer vibrant sensory experiences where visitors can purchase traditional crafts, kente cloth, beads, pottery, and wooden carvings. Engaging with local artisans provides insight into centuries-old traditions of weaving, pottery, and woodcarving that have been passed down through generations. The warm hospitality of the Ghanaian people, expressed through the traditional greeting "Akwaaba" (welcome), transforms a visit to the castles from a purely historical experience into a deeply human encounter with a culture that has endured and flourished despite the tragedies of the past.' },
      { style: 'h2', text: 'Planning Your Visit' },
      { style: 'normal', text: 'Both Cape Coast and Elmina Castles are located approximately 150 kilometres west of Accra, making them easily accessible for a day trip or a longer stay in the Central Region. The drive from Accra takes approximately three hours along a well-maintained highway that passes through picturesque coastal towns and lush tropical landscapes. Comprehensive guided tours are available at both castles and are highly recommended, as the guides provide invaluable historical context and personal insights that greatly enrich the experience. Tours last approximately one to two hours per castle, and we recommend visiting both for a complete understanding.' },
      { style: 'normal', text: 'The best time to visit is during the dry season from November to March, when the coastal weather is most pleasant and the skies are clearest. Comfortable walking shoes are essential, as the castle interiors feature uneven stone floors and steep staircases. Photography is permitted in most areas, though visitors are asked to be respectful in the dungeons and memorial spaces. Nearby attractions include Kakum National Park with its famous canopy walkway suspended 40 metres above the rainforest floor, and the beautiful beaches of the Central Region offering relaxation after the intensity of the castle tours.' },
      { style: 'normal', text: 'A visit to Cape Coast and Elmina Castles is an experience that will stay with you for the rest of your life. It is a journey into the depths of human history that challenges, educates, and ultimately inspires. In walking through these hallowed halls, we honour those who suffered and celebrate the resilience of the human spirit that has risen from the ashes of this tragic past to build a brighter future. The castles stand not merely as monuments to what was lost, but as enduring testaments to the strength, dignity, and unbreakable spirit of a people whose contributions to the world continue to resonate across generations.' },
    ]),
  },
  {
    title: 'Okavango Delta Safari: Botswana\'s Untamed Wilderness',
    slug: 'okavango-delta-safari-botswanas-untamed-wilderness',
    excerpt: 'In the heart of southern Africa lies one of the planet\'s most remarkable wilderness areas — the Okavango Delta. Unlike any other safari destination on Earth, this vast inland delta is formed not by flowing into the sea but by spreading across the arid plains of the Kalahari Desert, creating a lush, waterborne paradise that sustains an extraordinary diversity of wildlife. Designated as both a UNESCO World Heritage Site and one of the Seven Natural Wonders of Africa, the Okavango Delta offers a safari experience that is uniquely intimate, serene, and profoundly beautiful.\n\nWhat sets the Okavango apart from other African safari destinations is the unique way visitors explore it. Rather than traversing vast open plains in vehicles, visitors glide silently through papyrus-fringed waterways in a mokoro — a traditional dugout canoe poled by an expert local guide. This mode of exploration offers unparalleled proximity to wildlife and a sense of tranquillity that is difficult to replicate anywhere else. The delta\'s waterways teem with hippos, crocodiles, and over 400 bird species, while the islands host the Big Five and the largest concentration of African elephants on the continent, making it one of the most extraordinary wildlife destinations on Earth.\n\nThe Okavango Delta also represents a remarkable conservation success story, with a model that ensures local communities benefit directly from tourism revenue, creating powerful incentives for wildlife protection. Visitors can choose from ultra-luxurious lodges on private concessions to intimate mobile tented camps that offer a more authentic wilderness experience. Whether you come for the unparalleled wildlife viewing, the serenity of gliding through pristine waterways, or the world-class hospitality of Botswana\'s safari camps, the Okavango Delta delivers an experience that is nothing short of transformative.',
    categorySlug: 'destinations',
    tagSlugs: ['okavango-delta', 'safari', 'travel-guide'],
    readTime: 14,
    featuredImage: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?w=1200&q=80',
    metaTitle: 'Okavango Delta Safari Guide | Botswana Luxury Travel | Travio Africa',
    metaDescription: 'Your ultimate guide to an Okavango Delta safari in Botswana — mokoro excursions, wildlife encounters, luxury camps, and the best time to visit this unique wilderness paradise.',
    body: portableText([
      { style: 'normal', text: 'In the heart of southern Africa lies one of the planet\'s most remarkable wilderness areas — the Okavango Delta. Unlike any other safari destination on Earth, this vast inland delta is formed not by flowing into the sea but by spreading across the arid plains of the Kalahari Desert, creating a lush, waterborne paradise that sustains an extraordinary diversity of wildlife. Designated as both a UNESCO World Heritage Site and one of the Seven Natural Wonders of Africa, the Okavango Delta offers a safari experience that is uniquely intimate, serene, and profoundly beautiful — a place where the pace of life slows to the rhythm of the natural world.' },
      { style: 'h2', text: 'The Jewel of the Kalahari' },
      { style: 'normal', text: 'The Okavango Delta is a geological and ecological marvel unlike any other on Earth. Each year, floodwaters from the Angolan highlands travel over 1,000 kilometres to reach the delta, arriving during Botswana\'s dry season between June and August. The timing is remarkable — the flood peaks during the driest months, transforming 15,000 square kilometres of parched savannah into a mosaic of lagoons, channels, and islands. This annual inundation creates a wildlife spectacle of extraordinary proportions, as animals congregate in the delta\'s permanent waterways and lush vegetation in numbers that defy belief.' },
      { style: 'normal', text: 'What sets the Okavango apart from other African safari destinations is its intimate scale and the unique ways in which visitors can explore it. Rather than traversing vast open plains in vehicles, visitors explore the delta by mokoro — a traditional dugout canoe that glides silently through the papyrus-fringed waterways. This mode of exploration offers unparalleled proximity to wildlife and a sense of tranquillity that is difficult to replicate elsewhere. The only sounds are the gentle splash of the pole entering the water, the haunting call of an African fish eagle echoing across the channels, and the distant grunt of a hippopotamus surfacing from its afternoon slumber.' },
      { style: 'h2', text: 'Wildlife Encounters in the Delta' },
      { style: 'normal', text: 'The Okavango Delta supports an extraordinary concentration and diversity of wildlife that rivals any destination on the African continent. The Big Five are all present, though the delta is particularly renowned for its elephant population — the largest concentration of African elephants on the planet. Herds of several hundred individuals can be observed wading through the waterways, their massive bodies partially submerged as they bathe, socialise, and feed against a backdrop of towering sausage trees and ancient ebony forests. The sight of an elephant family crossing a channel at sunset is one of the most iconic images in African wildlife photography.' },
      { style: 'normal', text: 'The waterways themselves teem with life. Hippopotamuses wallow in the deeper channels, surfacing with explosive exhales that echo across the water and serve as a reminder of their status as one of Africa\'s most dangerous animals. Nile crocodiles bask on sandbanks, their ancient, unblinking eyes scanning for opportunity with a patience born of millions of years of evolution. The birdlife is exceptional, with over 400 species recorded, including the striking African jacana, which appears to walk on water as it steps across floating lily pads, and the magnificent Pel\'s fishing owl, a rare sighting that draws dedicated birders from around the world.' },
      { style: 'normal', text: 'Game drives on the delta\'s islands provide opportunities to encounter lions, leopards, cheetahs, and spotted hyenas, along with large herds of zebras, giraffes, and antelopes of every description. The endangered African wild dog, one of the continent\'s most efficient predators, thrives in the delta\'s pristine wilderness, and sightings of these highly social animals are a highlight for many visitors. The Moremi Game Reserve offers some of the most productive game viewing in the entire region, renowned for exceptional predator sightings and pristine wilderness conditions.' },
      { style: 'h2', text: 'Exploring by Mokoro: A Unique Perspective' },
      { style: 'normal', text: 'The mokoro experience is the heart and soul of an Okavango safari, offering a perspective on the wilderness that cannot be achieved by any other means. These traditional canoes, once carved from the majestic sausage tree but now more commonly crafted from fibreglass for conservation reasons, are poled by expert local guides who possess an intimate knowledge of the delta\'s waterways, wildlife, and ecology. As you glide silently through narrow channels lined with towering papyrus reeds, your guide will interpret the sights, sounds, and tracks that reveal the hidden life of the delta.' },
      { style: 'normal', text: 'Mokoro excursions typically take place in the early morning or late afternoon, when the light is soft and the wildlife is most active. The perspective from water level is transformative — you see the delta from an entirely different angle, one that emphasises the intricate connections between water, land, and life. Walking safaris on selected islands offer a complementary experience, allowing you to explore the delta\'s terrestrial ecosystems on foot under the guidance of armed and expert rangers who will introduce you to the smaller wonders of the bush.' },
      { style: 'h2', text: 'Luxury Safari Camps and Lodges' },
      { style: 'normal', text: 'The Okavango Delta is renowned for its exceptional accommodation, ranging from ultra-luxurious permanent lodges on private concessions to intimate mobile tented camps that offer a more authentic wilderness experience. Properties such as Mombo Camp, widely regarded as one of the finest safari camps in Africa, offer world-class guiding, exquisite cuisine, and tented suites that seamlessly blend five-star luxury with the natural environment. Private concessions provide the added benefit of exclusive access, with off-road driving and night drives permitted in areas where they are otherwise restricted.' },
      { style: 'normal', text: 'Many camps operate on an all-inclusive basis, covering accommodation, all meals and beverages, game drives, mokoro excursions, walking safaris, and transfers within the delta. The camp experience is an integral part of the safari, with communal dining under the stars, storytelling around the campfire, and the opportunity to connect with fellow travellers from around the world. The level of service at the delta\'s top camps is exceptional, with guide-to-guest ratios that ensure a personalised and deeply immersive experience.' },
      { style: 'h2', text: 'Photography in the Okavango Delta' },
      { style: 'normal', text: 'The Okavango Delta is a photographer\'s paradise, offering unique opportunities that cannot be replicated anywhere else in Africa. The interplay of light and water, particularly during the golden hours of early morning and late afternoon, creates magical conditions for landscape photography. The reflections of African ebony trees and papyrus reeds in the still waters of the delta\'s lagoons, combined with the warm glow of the African sun, produce images of extraordinary beauty. The intimate nature of mokoro excursions allows for close-up encounters with wildlife from a unique low-angle perspective.' },
      { style: 'normal', text: 'A versatile lens kit is essential for capturing the full range of photographic opportunities the delta offers. A telephoto lens of 200-400mm is ideal for wildlife photography from game vehicles and mokoros, while a wide-angle lens captures the sweeping landscapes and dramatic skies that define the Okavango experience. A polarising filter is invaluable for reducing glare on the water surface and enhancing colours. Camera equipment should be protected from water and dust, as the environment, while beautiful, can be challenging for sensitive electronics.' },
      { style: 'h2', text: 'Conservation and Community Tourism' },
      { style: 'normal', text: 'The Okavango Delta\'s conservation model is widely regarded as one of the most successful and innovative in Africa, demonstrating that wildlife and community development can thrive together. The establishment of wildlife management areas and community concessions has ensured that local communities benefit directly from tourism revenue, creating powerful economic incentives for conservation. Villages receive income from camp leases, employment opportunities, and community development funds, transforming local attitudes towards wildlife from competitors for resources to valuable assets worth protecting.' },
      { style: 'normal', text: 'Several community-run camps and initiatives allow visitors to engage directly with local communities, providing insights into traditional lifestyles and the challenges of living alongside Africa\'s most iconic wildlife. The Okavango Delta\'s unique ecosystem faces significant threats from climate change, which is altering rainfall patterns and flood cycles, as well as from proposed upstream water extraction and mining activities. Supporting responsible tourism operators who contribute to conservation efforts is one of the most effective ways visitors can help protect this fragile wilderness for future generations.' },
      { style: 'h2', text: 'What to Pack for an Okavango Safari' },
      { style: 'normal', text: 'Packing for an Okavango Delta safari requires careful consideration of the climate, the activities you will undertake, and the camp\'s specific dress code and facilities. Lightweight, neutral-coloured clothing in breathable natural fabrics such as cotton and linen is recommended for game drives, with long sleeves and trousers providing protection from the sun and insects. A warm fleece or lightweight jacket is essential for early morning game drives and night drives, when temperatures can drop significantly, particularly during the winter months from June to August.' },
      { style: 'normal', text: 'Sun protection is critical in the African bush, where the intensity of the sun can be deceptive even on overcast days. A wide-brimmed hat, polarised sunglasses, and high-SPF sunscreen are essential items that should be used without fail. Insect repellent is equally important, particularly during the wet season from November to March when mosquito activity is at its peak. A good quality pair of binoculars is perhaps the most important piece of equipment you will bring — the difference between seeing a distant leopard and experiencing every detail of its features through high-quality optics is the difference between a good safari and an unforgettable one.' },
      { style: 'normal', text: 'The Okavango Delta represents safari at its most refined and intimate. It is a place where the pace of life slows to the rhythm of the natural world, where each day brings encounters that inspire wonder and humility, and where the beauty of the African wilderness is revealed in its most subtle and breathtaking forms. For those seeking a safari experience that is both luxurious and authentic, where the boundaries between civilisation and wilderness dissolve into a seamless tapestry of unforgettable moments, the Okavango Delta is unsurpassed.' },
    ]),
  },
];

async function main() {
  console.log('=== Blog Seed Script (Supabase Remote) ===\n');

  const author = await prisma.user.findFirst({ where: { email: 'expeditiongoltd@gmail.com' } });
  if (!author) {
    console.error('Error: Author user not found (expeditiongoltd@gmail.com). Run prisma/seed.js first.');
    process.exit(1);
  }
  console.log(`Author: ${author.name} (${author.email})\n`);

  console.log('Seeding categories...');
  const categoryMap = {};
  for (const cat of CATEGORIES) {
    const record = await prisma.articleCategory.upsert({
      where: { slug: cat.slug },
      update: { name: cat.name, description: cat.description },
      create: { name: cat.name, slug: cat.slug, description: cat.description },
    });
    categoryMap[cat.slug] = record.id;
    console.log(`  Category: ${record.name} (${record.slug})`);
  }

  console.log('\nSeeding tags...');
  const tagMap = {};
  for (const tag of TAGS) {
    const record = await prisma.articleTag.upsert({
      where: { slug: tag.slug },
      update: { name: tag.name },
      create: { name: tag.name, slug: tag.slug },
    });
    tagMap[tag.slug] = record.id;
    console.log(`  Tag: ${record.name} (${record.slug})`);
  }

  console.log('\nSeeding articles...');
  for (const article of ARTICLES) {
    const categoryId = categoryMap[article.categorySlug];
    const tagIds = article.tagSlugs.map((s) => tagMap[s]).filter(Boolean);

    const existing = await prisma.article.findUnique({ where: { slug: article.slug } });

    let record;
    if (existing) {
      record = await prisma.article.update({
        where: { slug: article.slug },
        data: {
          title: article.title,
          excerpt: article.excerpt,
          body: article.body,
          featuredImage: article.featuredImage,
          metaTitle: article.metaTitle,
          metaDescription: article.metaDescription,
          readTime: article.readTime,
          status: 'PUBLISHED',
          publishedAt: new Date(),
          categoryId,
          authorId: author.id,
        },
      });
      console.log(`  Updated: ${record.title}`);
    } else {
      record = await prisma.article.create({
        data: {
          title: article.title,
          slug: article.slug,
          excerpt: article.excerpt,
          body: article.body,
          featuredImage: article.featuredImage,
          metaTitle: article.metaTitle,
          metaDescription: article.metaDescription,
          readTime: article.readTime,
          status: 'PUBLISHED',
          publishedAt: new Date(),
          locale: 'en',
          categoryId,
          authorId: author.id,
        },
      });
      console.log(`  Created: ${record.title}`);
    }

    await prisma.articleTagOnArticle.deleteMany({ where: { articleId: record.id } });
    if (tagIds.length > 0) {
      await prisma.articleTagOnArticle.createMany({
        data: tagIds.map((tagId) => ({ articleId: record.id, tagId })),
      });
    }
  }

  console.log(`\n✓ ${ARTICLES.length} articles seeded successfully.`);
}

main()
  .catch((e) => {
    console.error('\nSeed failed:', e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
