-- Supplier-selectable payout cadence (GetYourGuide-style).
--
-- A value on SupplierProfile.payoutCycle enrols the supplier in automated
-- payout runs; NULL keeps the legacy twice-monthly manual withdrawal windows
-- (Africa and any brand that has not adopted the schedule feature). The
-- columns are nullable + the enum is new, so this migration is purely additive
-- and cannot change any existing behaviour.

-- CreateEnum
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'PayoutCycle') THEN
    CREATE TYPE "PayoutCycle" AS ENUM ('WEEKLY', 'TWICE_MONTHLY', 'MONTHLY');
  END IF;
END $$;

-- AlterTable
ALTER TABLE "SupplierProfile"
  ADD COLUMN IF NOT EXISTS "payoutCycle" "PayoutCycle",
  ADD COLUMN IF NOT EXISTS "payoutCycleEffectiveAt" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "payoutCyclePending" "PayoutCycle",
  ADD COLUMN IF NOT EXISTS "payoutCyclePendingAt" TIMESTAMP(3);

-- AlterTable
ALTER TABLE "PayoutRequest"
  ADD COLUMN IF NOT EXISTS "autoGenerated" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "runKey" TEXT;

-- CreateIndex (hard idempotency guard for scheduler-generated runs)
CREATE UNIQUE INDEX IF NOT EXISTS "PayoutRequest_runKey_key" ON "PayoutRequest"("runKey");

-- Notification type for a payout schedule change. ADD VALUE is safe here: the
-- value is not used inside this migration's transaction.
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'PAYOUT_SCHEDULE_UPDATED';
