-- AlterEnum
-- Producers already emit these per-user notification types but the values were
-- missing from the NotificationType enum, so Prisma rejected every create and
-- the supplier/customer bell never received them:
--   supplier: BOOKING_PAYMENT_FAILED, DISPUTE_OPENED, DISPUTE_RESOLVED, REFUND_ISSUED (adminFinance), TEAM_INVITE_ACCEPTED
--   customer: PAYMENT_FAILED, PAYMENT_COMPLETED, PAYMENT_ACTION_REQUIRED, BOOKING_AWAITING_CONFIRMATION
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'BOOKING_AWAITING_CONFIRMATION';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'BOOKING_PAYMENT_FAILED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'PAYMENT_FAILED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'PAYMENT_COMPLETED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'PAYMENT_ACTION_REQUIRED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'DISPUTE_OPENED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'DISPUTE_RESOLVED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'REFUND_ISSUED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'TEAM_INVITE_ACCEPTED';
