-- AlterTable
ALTER TABLE "Booking" ADD COLUMN IF NOT EXISTS "offerName" TEXT;
ALTER TABLE "Booking" ADD COLUMN IF NOT EXISTS "offerPromoCode" TEXT;
ALTER TABLE "Booking" ADD COLUMN IF NOT EXISTS "offerDiscountType" TEXT;
ALTER TABLE "Booking" ADD COLUMN IF NOT EXISTS "offerDiscountPct" INTEGER;
ALTER TABLE "Booking" ADD COLUMN IF NOT EXISTS "offerDiscountFix" DOUBLE PRECISION;
