const prisma = require('../services/prismaClient');
const catchAsync = require('../services/catchAsync');
const AppError = require('../services/appError');
const { getRequestWindow, getCurrentCycle, getClearanceBufferDays } = require('../services/payoutCycles');
const {
  getSupplierPayoutPlan,
  updateSupplierPayoutPlan,
  selectEligibleBookings,
  resolvePayoutMethod,
  createRequestsForBookings,
  notifyPayoutRequestsCreated,
} = require('../services/payoutRuns');
const { logActivity } = require('../services/auditLogger');
const { payoutBookingsWhere } = require('../services/financeHelpers');
const { buildInvoiceEstimate } = require('../services/invoiceService');

// ── Finance v2 + v3 — supplier-facing payout/invoice endpoints ──
// Mounted at /finance (see routes/financeRoutes.js). All routes resolve the
// acting supplier via resolveSupplier + requireTeamPermission in the router.
// v3 = GetYourGuide-style automatic invoices (balance = unpaid invoices,
// next payout = pending-window projection); v2 PayoutRequest endpoints remain
// for the legacy flow and history.

function toNumber(v) {
  return v == null ? 0 : parseFloat(v);
}

function round2(n) {
  return Math.round((n + Number.EPSILON) * 100) / 100;
}

function serializeRequest(request) {
  return {
    ...request,
    amount: toNumber(request.amount),
    items: (request.items || []).map((it) => ({
      ...it,
      grossAmount: toNumber(it.grossAmount),
      platformCommission: toNumber(it.platformCommission),
      supplierPayout: toNumber(it.supplierPayout),
    })),
  };
}

/**
 * GET /finance/summary
 * Finance page data, GetYourGuide semantics on top of the legacy v2 fields:
 *  - balance     "Your balance" — unpaid (INVOICED/APPROVED) invoices, per currency
 *  - nextPayout  the pending window's projection BEFORE it is invoiced: only
 *                ELIGIBLE money, with the exact activity-date range and
 *                processing dates; null for legacy (window-managed) suppliers
 * The legacy v2 fields (availableBalance/pendingClearance/inReview/
 * withdrawalWindow/nextEligibleAt) are kept until the UI migrates to the new
 * model, so the current Finance page keeps rendering.
 */
exports.getFinanceSummary = catchAsync(async (req, res) => {
  const supplierId = req.supplierId;

  const [eligible, pendingClearance, activeRequests, paidOut, window, cycle, bufferDays, payoutPlan, nextPending, payoutCounts, openInvoices, paidInvoices] = await Promise.all([
    prisma.booking.aggregate({
      where: payoutBookingsWhere({ supplierId, payoutStatus: 'ELIGIBLE' }),
      _sum: { supplierPayout: true },
      _count: true,
    }),
    prisma.booking.aggregate({
      where: payoutBookingsWhere({ supplierId, payoutStatus: 'PENDING' }),
      _sum: { supplierPayout: true },
      _count: true,
    }),
    prisma.payoutRequest.findMany({
      where: { supplierId, status: { in: ['PROCESSING', 'APPROVED'] } },
      orderBy: { createdAt: 'desc' },
      // Everything the dashboard's "payout in review" card needs: what the money
      // is, how many bookings it covers, and whether the supplier asked for it
      // or the scheduler did. Without this the dashboard can only say
      // "1 request(s)" and cannot explain that the money is already on its way.
      select: {
        id: true,
        requestNumber: true,
        amount: true,
        currency: true,
        status: true,
        bookingCount: true,
        autoGenerated: true,
        cycleLabel: true,
        cycleStartDate: true,
        cycleEndDate: true,
        createdAt: true,
      },
    }),
    prisma.payout.aggregate({
      where: { supplierId, status: 'PAID' },
      _sum: { amount: true },
    }),
    getRequestWindow(),
    getCurrentCycle(),
    getClearanceBufferDays(),
    getSupplierPayoutPlan(supplierId),
    // The soonest PENDING booking that will actually clear, so the dashboard can
    // say when money is next due instead of leaving the supplier to guess.
    prisma.booking.findFirst({
      where: {
        ...payoutBookingsWhere({ supplierId, payoutStatus: 'PENDING' }),
        // Match the eligibility sweep: a booking under an open dispute stays
        // frozen, so it must not be promised a clearance date.
        disputes: { none: { status: { in: ['OPEN', 'UNDER_REVIEW'] } } },
      },
      orderBy: { travelDate: 'asc' },
      select: { travelDate: true },
    }),
    // How many bookings sit in each payout bucket. The earnings table can be
    // filtered down to an empty set while the supplier holds plenty of bookings
    // in another bucket, and "No earnings yet" for someone with 15 bookings is
    // simply false — these counts are what let the page say where they went.
    prisma.booking.groupBy({
      by: ['payoutStatus'],
      where: { tour: { supplierId }, isSimulated: false },
      _count: { _all: true },
    }),
    // Finance v3: unpaid invoices = "Your balance"; paid invoices count into
    // the lifetime paid-out total alongside the legacy Payout rows. Approved
    // (APPROVED) invoices are still owed to the supplier — the money is
    // authorized but has not moved — so they count as balance too.
    prisma.invoice.findMany({
      where: { supplierId, status: { in: ['INVOICED', 'APPROVED'] } },
      orderBy: { invoicedAt: 'asc' },
      select: {
        id: true,
        invoiceNumber: true,
        currency: true,
        netTotal: true,
        bookingCount: true,
        cycleLabel: true,
        paymentScheduledAt: true,
      },
    }),
    prisma.invoice.aggregate({
      where: { supplierId, status: 'PAID' },
      _sum: { netTotal: true },
    }),
  ]);

  // ── Finance v3: "Your balance" = the sum of unpaid invoices, by currency ──
  const balanceByCurrency = {};
  let balanceBookingCount = 0;
  for (const inv of openInvoices) {
    balanceByCurrency[inv.currency] = (balanceByCurrency[inv.currency] || 0) + toNumber(inv.netTotal);
    balanceBookingCount += inv.bookingCount;
  }

  // ── Finance v3: "Next payout" = live projection for the pending window.
  // Includes future confirmed tours; recalculates on every load; becomes the
  // balance once the window's invoice date arrives. Legacy (window-managed)
  // suppliers have no cadence, so they get null and keep the v2 flow. ──
  const nextPayout = payoutPlan.autoManaged && payoutPlan.cycle
    ? await buildInvoiceEstimate({ supplierId, cycle: payoutPlan.cycle })
    : null;

  // Group active request totals by currency
  const inReview = {};
  for (const r of activeRequests) {
    inReview[r.currency] = (inReview[r.currency] || 0) + toNumber(r.amount);
  }

  // Which window decides whether "Request payout" is available.
  //
  // Enrolled suppliers are paid via the invoice engine (v3): their money is
  // invoiced automatically on their cadence, so they have no manual request
  // button and no legacy withdrawal window (the summary still carries an
  // invoice-sourced window so the UI can describe the processing dates). Legacy
  // (unmigrated) suppliers keep the twice-monthly calendar window, which is
  // unrelated to the v2 run-day window a weekly cadence used to imply.
  let requestWindow;
  if (payoutPlan.autoManaged) {
    requestWindow = {
      open: true,
      source: 'invoice',
      cycleLabel: payoutPlan.nextRunPeriodLabel || null,
      opensAt: null,
      closesAt: null,
    };
  } else {
    requestWindow = {
      open: window.open,
      opensAt: window.start,
      closesAt: window.end,
      cycleLabel: window.label,
      source: 'window',
    };
  }

  res.status(200).json({
    status: 'success',
    data: {
      // ── Finance v3 (GetYourGuide model) ──
      balance: {
        byCurrency: Object.entries(balanceByCurrency).map(([currency, amount]) => ({ currency, amount: round2(amount) })),
        bookingCount: balanceBookingCount,
        openInvoiceCount: openInvoices.length,
      },
      nextPayout,
      // ── Legacy v2 fields (kept until the UI migrates) ──
      availableBalance: {
        amount: toNumber(eligible._sum.supplierPayout),
        bookingCount: eligible._count,
        currency: 'USD',
      },
      pendingClearance: {
        amount: toNumber(pendingClearance._sum.supplierPayout),
        bookingCount: pendingClearance._count,
        clearanceBufferDays: bufferDays,
      },
      inReview: {
        total: activeRequests.reduce((s, r) => s + toNumber(r.amount), 0),
        byCurrency: inReview,
        requestCount: activeRequests.length,
        bookingCount: activeRequests.reduce((s, r) => s + r.bookingCount, 0),
        // Newest request still in flight, in full. This is what lets the page
        // lead with "Payout in review - $1,263.46" instead of a disabled
        // "Request payout - $0.00" while finance is holding the balance.
        latestRequest: activeRequests[0]
          ? {
              id: activeRequests[0].id,
              reference: activeRequests[0].requestNumber,
              amount: toNumber(activeRequests[0].amount),
              currency: activeRequests[0].currency,
              status: activeRequests[0].status,
              bookingCount: activeRequests[0].bookingCount,
              autoGenerated: activeRequests[0].autoGenerated,
              cycleLabel: activeRequests[0].cycleLabel,
              cycleStartDate: activeRequests[0].cycleStartDate,
              cycleEndDate: activeRequests[0].cycleEndDate,
              createdAt: activeRequests[0].createdAt,
            }
          : null,
      },
      // Booking count per payout bucket, always every key present so the UI
      // never has to distinguish "0" from "missing".
      payoutCounts: Object.fromEntries(
        ['PENDING', 'ELIGIBLE', 'REQUESTED', 'INVOICED', 'PAID', 'DISPUTED', 'CANCELLED'].map((key) => [
          key,
          Number(payoutCounts.find((r) => r.payoutStatus === key)?._count?._all || 0),
        ])
      ),
      // When the soonest uncleared booking becomes withdrawable: its travel date
      // plus the clearance buffer, which is exactly the sweep's own cutoff.
      nextEligibleAt: nextPending?.travelDate
        ? new Date(new Date(nextPending.travelDate).getTime() + bufferDays * 24 * 60 * 60 * 1000)
        : null,
      paidOut: {
        // Legacy Payout rows + v3 paid invoices.
        total: round2(toNumber(paidOut._sum.amount) + toNumber(paidInvoices._sum.netTotal)),
      },
      currentCycle: { start: cycle.start, end: cycle.end, label: cycle.label },
      // The supplier's payout schedule (auto-generated runs). `autoManaged`
      // false means the legacy window-based manual flow below still applies.
      payoutPlan,
      withdrawalWindow: requestWindow,
    },
  });
});

/**
 * GET /finance/invoices?status=INVOICED&page=1&limit=20
 * The supplier's invoice history (finance v3): every generated invoice with
 * its money snapshot, window label and payment status. This is the page's
 * "Your balance" (status INVOICED or APPROVED — approved-but-unpaid still
 * counts) and paid-history source.
 */
exports.getMyInvoices = catchAsync(async (req, res) => {
  const supplierId = req.supplierId;
  const page = Math.max(1, parseInt(req.query.page, 10) || 1);
  const limit = Math.min(100, Math.max(1, parseInt(req.query.limit, 10) || 20));
  const rawStatus = req.query.status ? String(req.query.status).toUpperCase() : null;
  const status = rawStatus && ['INVOICED', 'APPROVED', 'PAID'].includes(rawStatus) ? rawStatus : undefined;

  const where = { supplierId, ...(status ? { status } : {}) };

  const [invoices, totalCount] = await Promise.all([
    prisma.invoice.findMany({
      where,
      orderBy: { invoicedAt: 'desc' },
      skip: (page - 1) * limit,
      take: limit,
      select: {
        id: true,
        invoiceNumber: true,
        status: true,
        cycle: true,
        cycleLabel: true,
        cycleStartDate: true,
        cycleEndDate: true,
        invoicedAt: true,
        paymentScheduledAt: true,
        paidAt: true,
        reference: true,
        grossTotal: true,
        commissionTotal: true,
        netTotal: true,
        currency: true,
        bookingCount: true,
        payoutMethodId: true,
        _count: { select: { items: true } },
      },
    }),
    prisma.invoice.count({ where }),
  ]);

  res.status(200).json({
    status: 'success',
    data: {
      invoices: invoices.map((i) => ({
        id: i.id,
        invoiceNumber: i.invoiceNumber,
        status: i.status,
        cycle: i.cycle,
        cycleLabel: i.cycleLabel,
        cycleStartDate: i.cycleStartDate,
        cycleEndDate: i.cycleEndDate,
        invoicedAt: i.invoicedAt,
        paymentScheduledAt: i.paymentScheduledAt,
        paidAt: i.paidAt,
        reference: i.reference,
        grossTotal: toNumber(i.grossTotal),
        commissionTotal: toNumber(i.commissionTotal),
        netTotal: toNumber(i.netTotal),
        currency: i.currency,
        bookingCount: i.bookingCount,
        itemCount: i._count.items,
        payoutMethodId: i.payoutMethodId,
      })),
      pagination: {
        currentPage: page,
        limit,
        totalCount,
        totalPages: Math.ceil(totalCount / limit),
      },
    },
  });
});

/**
 * GET /finance/earnings?payoutStatus=ELIGIBLE&page=1&limit=20
 * Booking-level earnings list with payout lifecycle filter.
 */
exports.getEarnings = catchAsync(async (req, res) => {
  const supplierId = req.supplierId;
  const page = Math.max(1, parseInt(req.query.page, 10) || 1);
  const limit = Math.min(500, Math.max(1, parseInt(req.query.limit, 10) || 20));
  const skip = (page - 1) * limit;

  const where = { tour: { supplierId }, isSimulated: false };
  if (req.query.payoutStatus) {
    const statuses = String(req.query.payoutStatus).split(',').map((s) => s.trim()).filter(Boolean);
    where.payoutStatus = { in: statuses };
  }
  if (req.query.currency) where.currency = req.query.currency;

  const [bookings, totalCount, aggregates] = await Promise.all([
    prisma.booking.findMany({
      where,
      include: {
        tour: { select: { id: true, title: true, coverPhoto: true } },
        customer: { select: { id: true, name: true, email: true } },
        payoutRequestItems: { include: { payoutRequest: { select: { id: true, requestNumber: true, status: true } } } },
        disputes: { where: { status: { in: ['OPEN', 'UNDER_REVIEW'] } }, select: { id: true, disputeNumber: true, status: true } },
      },
      orderBy: { travelDate: 'desc' },
      skip,
      take: limit,
    }),
    prisma.booking.count({ where }),
    prisma.booking.aggregate({
      where,
      _sum: { grossAmount: true, supplierPayout: true, platformCommission: true },
    }),
  ]);

  res.status(200).json({
    status: 'success',
    data: {
      earnings: bookings.map((b) => ({
        id: b.id,
        bookingNumber: b.bookingNumber,
        travelDate: b.travelDate,
        paidAt: b.paidAt,
        grossAmount: toNumber(b.grossAmount),
        supplierPayout: toNumber(b.supplierPayout),
        platformCommission: toNumber(b.platformCommission),
        commissionRate: toNumber(b.commissionRate),
        currency: b.currency,
        payoutStatus: b.payoutStatus,
        status: b.status,
        tour: b.tour,
        customer: b.customer,
        payoutRequest: b.payoutRequestItems?.[0]
          ? { id: b.payoutRequestItems[0].payoutRequest.id, requestNumber: b.payoutRequestItems[0].payoutRequest.requestNumber, status: b.payoutRequestItems[0].payoutRequest.status }
          : null,
        openDispute: b.disputes?.[0] || null,
      })),
      summary: {
        grossAmount: toNumber(aggregates._sum.grossAmount),
        supplierPayout: toNumber(aggregates._sum.supplierPayout),
        platformCommission: toNumber(aggregates._sum.platformCommission),
      },
      pagination: {
        currentPage: page,
        limit,
        totalCount,
        totalPages: Math.ceil(totalCount / limit),
      },
    },
  });
});

/**
 * GET /finance/charges
 * The supplier's cancellation-fee ledger (open fees will be netted off their
 * next payout request; settled ones show which request collected them).
 */
exports.getSupplierCharges = catchAsync(async (req, res, next) => {
  const supplierId = req.supplierId;
  if (!supplierId) return next(new AppError('Not authorized', 401));

  const charges = await prisma.supplierCharge.findMany({
    where: { supplierId },
    orderBy: { createdAt: 'desc' },
    take: 100,
    include: {
      booking: { select: { id: true, bookingNumber: true, travelDate: true, status: true } },
      payoutRequest: { select: { id: true, requestNumber: true, status: true } },
    },
  });

  const openTotals = {};
  for (const c of charges) {
    if (c.status !== 'OPEN') continue;
    openTotals[c.currency] = Math.round(((openTotals[c.currency] || 0) + toNumber(c.amount)) * 100) / 100;
  }

  res.status(200).json({
    status: 'success',
    data: {
      openTotals,
      charges: charges.map((c) => ({
        id: c.id,
        amount: toNumber(c.amount),
        currency: c.currency,
        reason: c.reason,
        status: c.status,
        notes: c.notes,
        createdAt: c.createdAt,
        settledAt: c.settledAt,
        bookingId: c.bookingId,
        bookingNumber: c.booking?.bookingNumber || null,
        travelDate: c.booking?.travelDate || null,
        payoutRequestId: c.payoutRequestId,
        payoutRequestNumber: c.payoutRequest?.requestNumber || null,
      })),
    },
  });
});

/**
 * POST /finance/payout/request
 * Body: { bookingIds?: string[], payoutMethodId?: string, notes?: string }
 * - Omitting bookingIds selects ALL eligible bookings.
 * - Mixed currencies are split into one request per currency.
 */
exports.createPayoutRequest = catchAsync(async (req, res, next) => {
  const supplierId = req.supplierId;
  const { bookingIds, payoutMethodId, notes } = req.body || {};

  // Enrolled suppliers are paid via invoices — automatically on their cadence.
  // The v2 manual batch flow is retired for them: a legacy PayoutRequest would
  // open a second payment channel the invoice engine has no visibility into,
  // and the v2 auto-run that used to sweep those batches is superseded. Legacy
  // (unmigrated) suppliers keep the calendar-window flow below, so nothing
  // about their existing flow changes.
  const plan = await getSupplierPayoutPlan(supplierId);
  if (plan.autoManaged) {
    return next(new AppError(
      `Payouts on your account are generated automatically via invoices (${plan.scheduleLabel}). `
      + 'Your earnings are invoiced and paid on that schedule — no manual request is needed.',
      409
    ));
  }

  const window = await getRequestWindow();
  if (!window.open) {
    return next(new AppError(
      `The withdrawal window is closed. It opens ${window.start.toISOString().slice(0, 10)} for the "${window.label}" cycle.`,
      400
    ));
  }
  const cycleWindow = { start: window.cycle.start, end: window.cycle.end, label: window.cycle.label };

  // One open request per supplier per period. Without this a supplier could
  // submit repeatedly while an earlier request for the same period is still
  // sitting in the admin queue, and the queue grows a row per attempt.
  //
  // This is about queue hygiene, not double payment — that is prevented
  // upstream: selectEligibleBookings excludes bookings already on a request,
  // so a manual request claims every eligible booking and the auto-generated
  // run then finds none and skips. The scheduler is additionally idempotent
  // via runKey, and is deliberately not subject to this guard.
  //
  // Terminal states (rejected/cancelled/completed) release the bookings and do
  // not block.
  const openForPeriod = await prisma.payoutRequest.findFirst({
    where: {
      supplierId,
      status: { in: ['PROCESSING', 'APPROVED'] },
      cycleStartDate: { lte: cycleWindow.end },
      cycleEndDate: { gte: cycleWindow.start },
    },
    orderBy: { createdAt: 'desc' },
    select: { requestNumber: true },
  });
  if (openForPeriod) {
    return next(new AppError(
      `You already have an open payout request (${openForPeriod.requestNumber}) for this period. `
      + 'It has to be approved, rejected or cancelled before you can submit another.',
      409
    ));
  }

  // Validate payout method ownership + verification when provided
  let method;
  try {
    method = await resolvePayoutMethod({ supplierId, payoutMethodId });
  } catch (err) {
    return next(err);
  }
  if (!method) {
    return next(new AppError('Add and verify a payout method before requesting a payout', 400));
  }

  // Resolve candidate bookings
  const candidates = await selectEligibleBookings({ supplierId, bookingIds });

  if (candidates.length === 0) {
    return next(new AppError('No eligible bookings found for a payout request', 400));
  }
  if (Array.isArray(bookingIds) && bookingIds.length > candidates.length) {
    return next(new AppError('Some selected bookings are not eligible (already requested, disputed, or still clearing)', 400));
  }

  let requests;
  let totalFeesDeducted;
  try {
    const result = await createRequestsForBookings({
      supplierId,
      bookings: candidates,
      method,
      cycleWindow,
      notes: notes || null,
      autoGenerated: false,
    });
    requests = result.requests;
    totalFeesDeducted = result.feesDeducted;
  } catch (err) {
    return next(err);
  }

  await logActivity({
    userId: req.user.id,
    action: 'payout_request.created',
    resource: 'PayoutRequest',
    resourceId: requests[0].id,
    metadata: {
      requests: requests.map((r) => ({ id: r.id, currency: r.currency, amount: toNumber(r.amount), bookings: r.bookingCount })),
      feesDeducted: Math.round(totalFeesDeducted * 100) / 100,
    },
  });

  await notifyPayoutRequestsCreated({ requests, supplierId, autoGenerated: false }).catch((err) =>
    console.error('[Finance] Payout notification failed:', err.message)
  );

  res.status(201).json({
    status: 'success',
    data: { requests: requests.map(serializeRequest) },
  });
});

/**
 * GET /finance/payouts/requests?page=&limit=&status=
 */
exports.getPayoutRequests = catchAsync(async (req, res) => {
  const supplierId = req.supplierId;
  const page = Math.max(1, parseInt(req.query.page, 10) || 1);
  const limit = Math.min(100, Math.max(1, parseInt(req.query.limit, 10) || 20));

  const where = { supplierId };
  if (req.query.status) {
    where.status = { in: String(req.query.status).split(',').map((s) => s.trim()).filter(Boolean) };
  }

  const [requests, totalCount] = await Promise.all([
    prisma.payoutRequest.findMany({
      where,
      include: {
        items: { include: { booking: { select: { bookingNumber: true, travelDate: true, tour: { select: { title: true } } } } } },
        payoutMethod: { select: { id: true, type: true, bankName: true, paypalEmail: true, accountName: true, mobileProvider: true, mobileNumber: true } },
      },
      orderBy: { createdAt: 'desc' },
      skip: (page - 1) * limit,
      take: limit,
    }),
    prisma.payoutRequest.count({ where }),
  ]);

  res.status(200).json({
    status: 'success',
    data: {
      requests: requests.map(serializeRequest),
      pagination: { currentPage: page, limit, totalCount, totalPages: Math.ceil(totalCount / limit) },
    },
  });
});

/**
 * GET /finance/payouts/requests/:id
 */
exports.getPayoutRequestById = catchAsync(async (req, res, next) => {
  const request = await prisma.payoutRequest.findFirst({
    where: { id: req.params.id, supplierId: req.supplierId },
    include: {
      items: { include: { booking: { select: { bookingNumber: true, travelDate: true, grossAmount: true, currency: true, tour: { select: { title: true } } } } } },
      payoutMethod: true,
    },
  });
  if (!request) return next(new AppError('Payout request not found', 404));

  res.status(200).json({ status: 'success', data: { request: serializeRequest(request) } });
});

/**
 * PATCH /finance/payouts/requests/:id/cancel
 * Supplier can cancel their own request while it is still PROCESSING.
 */
exports.cancelPayoutRequest = catchAsync(async (req, res, next) => {
  const request = await prisma.payoutRequest.findFirst({
    where: { id: req.params.id, supplierId: req.supplierId, status: 'PROCESSING' },
    include: { items: true },
  });
  if (!request) return next(new AppError('Payout request not found or can no longer be cancelled', 404));

  await prisma.$transaction(async (tx) => {
    await tx.payoutRequest.update({
      where: { id: request.id },
      data: { status: 'CANCELLED', notes: 'Cancelled by supplier' },
    });
    await tx.booking.updateMany({
      where: { id: { in: request.items.map((i) => i.bookingId) }, payoutStatus: 'REQUESTED' },
      data: { payoutStatus: 'ELIGIBLE' },
    });
  });

  await logActivity({
    userId: req.user.id,
    action: 'payout_request.cancelled',
    resource: 'PayoutRequest',
    resourceId: request.id,
    metadata: { requestNumber: request.requestNumber },
  });

  res.status(200).json({ status: 'success', data: { request: { id: request.id, status: 'CANCELLED' } } });
});

/**
 * GET /finance/disputes
 * Disputes opened against this supplier's bookings.
 */
exports.getDisputes = catchAsync(async (req, res) => {
  const page = Math.max(1, parseInt(req.query.page, 10) || 1);
  const limit = Math.min(100, Math.max(1, parseInt(req.query.limit, 10) || 20));
  const where = { supplierId: req.supplierId };
  if (req.query.status) {
    where.status = { in: String(req.query.status).split(',').map((s) => s.trim()).filter(Boolean) };
  }

  const [disputes, totalCount] = await Promise.all([
    prisma.dispute.findMany({
      where,
      include: {
        booking: { select: { bookingNumber: true, travelDate: true, grossAmount: true, currency: true, tour: { select: { title: true } } } },
        opener: { select: { name: true, email: true } },
      },
      orderBy: { createdAt: 'desc' },
      skip: (page - 1) * limit,
      take: limit,
    }),
    prisma.dispute.count({ where }),
  ]);

  res.status(200).json({
    status: 'success',
    data: {
      disputes: disputes.map((d) => ({
        ...d,
        refundAmount: d.refundAmount == null ? null : toNumber(d.refundAmount),
        booking: d.booking ? { ...d.booking, grossAmount: toNumber(d.booking.grossAmount) } : null,
      })),
      pagination: { currentPage: page, limit, totalCount, totalPages: Math.ceil(totalCount / limit) },
    },
  });
});

/**
 * GET /finance/payout-settings
 * The supplier's automated payout schedule: current cadence, next run date,
 * and any change scheduled for the 1st of next month.
 */
exports.getPayoutSettings = catchAsync(async (req, res, next) => {
  const supplierId = req.supplierId;
  if (!supplierId) return next(new AppError('Not authorized', 401));

  const plan = await getSupplierPayoutPlan(supplierId);
  res.status(200).json({ status: 'success', data: plan });
});

/**
 * PATCH /finance/payout-settings
 * Body: { cycle: 'TWICE_MONTHLY' | 'MONTHLY' }
 *
 * Changes take effect on the 1st of the following month (GetYourGuide rule) so
 * a supplier can never switch mid-cycle; a first enrolment applies immediately
 * so they are never left unmanaged.
 */
exports.updatePayoutSettings = catchAsync(async (req, res, next) => {
  const supplierId = req.supplierId;
  if (!supplierId) return next(new AppError('Not authorized', 401));

  const { cycle } = req.body || {};
  if (!cycle) return next(new AppError('A payout cycle is required', 400));

  const plan = await updateSupplierPayoutPlan({
    supplierId,
    cycle: String(cycle).toUpperCase(),
    actorUserId: req.user?.id || null,
    actorEmail: req.user?.email || null,
  });

  const { enqueueNotification } = require('../services/queue');
  const labelFor = (value) => (plan.options.find((o) => o.value === value) || {}).label || value;

  enqueueNotification({
    userId: supplierId,
    type: 'PAYOUT_SCHEDULE_UPDATED',
    title: 'Payout schedule updated',
    message: plan.pendingCycle
      ? `Your payout schedule will switch to "${labelFor(plan.pendingCycle)}" on ${new Date(plan.pendingEffectiveAt).toISOString().slice(0, 10)}.`
      : `Your payout schedule is now "${labelFor(plan.cycle)}".${plan.nextRunAt ? ` Your next payout is ${new Date(plan.nextRunAt).toISOString().slice(0, 10)}.` : ''}`,
    data: { cycle: plan.cycle, pendingCycle: plan.pendingCycle, nextRunAt: plan.nextRunAt },
  }).catch(() => {});

  res.status(200).json({ status: 'success', data: plan });
});
